version: '3'

services: 
    laravel-app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./:/usr/share/nginx
        networks: 
            - app-network
    mysql-app:
        image: mysql:5.7.22
        volumes:
            - .docker/dbdata:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks: 
            - app-network
networks:
    app-network:
        driver: bridge

